# version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: scspace-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PWD}
      TZ: Asia/Seoul # 시간대 설정
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # UTF-8 인코딩 설정
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - scspace-infra-network

  redis:
    image: redis:latest
    container_name: scspace-redis
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PWD}
    command: redis-server --requirepass ${REDIS_PWD}
    volumes:
      - redis-data:/data
    networks:
      - scspace-infra-network


networks:
  scspace-infra-network:
    external: true

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
