version: "3.9"

services:
  nginx:
    container_name: scspace-nginx
    image: nginx:1.27
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      BASIC_URL: "http://localhost"
    command: >-
      /bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'
    volumes:
      - type: bind
        source: ${NGINX_CONFIG:-./infra/nginx/nginx.prod.conf}
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ${NGINX_CERT_DIR:-./infra/certbot/conf}
        target: /etc/letsencrypt
        read_only: true
      - type: bind
        source: ${NGINX_CERT_WEBROOT:-./infra/certbot/www}
        target: /var/www/certbot
        read_only: true
    networks:
      - scspace-internal-network

  certbot:
    container_name: scspace-certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${NGINX_CERT_DIR:-./infra/certbot/conf}
        target: /etc/letsencrypt
      - type: bind
        source: ${NGINX_CERT_WEBROOT:-./infra/certbot/www}
        target: /var/www/certbot
    entrypoint: >-
      /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'

networks:
  scspace-internal-network:
    external: true
    name: scspace-internal-network
