version: "3.9"

services:
  client:
    container_name: scspace-client
    build:
      context: ../..
      dockerfile: packages/client/Dockerfile
    image: scspace-client:latest
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      PORT: ${CLIENT_PORT}
    expose:
      - "${CLIENT_PORT}"
    networks:
      - scspace-internal-network

networks:
  scspace-internal-network:
    external: true
    name: scspace-internal-network
