version: "3.9"

services:
  server:
    container_name: scspace-server
    build:
      context: ../..
      dockerfile: packages/server/Dockerfile
    image: scspace-server:latest
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      NODE_ENV: production
      SERVER_PORT: ${SERVER_PORT:-3001}
      MYSQL_HOST: ${MYSQL_HOST:-scspace-mysql}
      MYSQL_PORT: ${DB_PORT:-3306}
      TZ: Asia/Seoul
    expose:
      - "${SERVER_PORT:-3001}"
    volumes:
      - ../../packages/server/uploads:/workspace/packages/server/uploads
    networks:
      - scspace-internal-network
      - scspace-infra-network

networks:
  scspace-internal-network:
    external: true
    name: scspace-internal-network
  scspace-infra-network:
    external: true
    name: scspace-infra-network
